const arabCountriesCities = [
  {
    country: "Morocco",
    cities: [
      "Casablanca",
      "Rabat",
      "Fes",
      "Marrakech",
      "Tangier",
      "Agadir",
      "Meknes",
      "Oujda",
      "Kenitra",
      "Tetouan",
      "El Jadida",
      "Nador",
      "Beni Mellal",
      "Khenifra",
      "Ksar el-Kebir",
      "Safi",
      "Salé",
      "Azrou",
      "Ifrane",
      "Ouarzazate",
      "Khouribga",
      "Goulmima",
      "Taroudant",
      "Taza",
      "Midelt",
      "Chefchaouen",
      "Sidi Kacem",
      "Sidi Slimane",
      "Errachidia",
      "Al Hoceima",
    ],
  },
  {
    country: "Egypt",
    cities: [
      "Cairo",
      "Alexandria",
      "Giza",
      "Shubra El Kheima",
      "Port Said",
      "Suez",
      "Mansoura",
      "Tanta",
      "Ismailia",
      "Fayoum",
      "6th October",
      "Damanhur",
      "Asyut",
      "Minya",
      "Qena",
      "Luxor",
      "Damietta",
      "Benha",
      "Beni Suef",
      "Zagazig",
      "Marsa Matruh",
      "Sohag",
      "Kafr el-Sheikh",
      "Daqahlia",
      "Aswan",
      "North Sinai",
      "South Sinai",
      "Gharbia",
      "Helwan",
      "Suez",
    ],
  },
  {
    country: "Saudi Arabia",
    cities: [
      "Riyadh",
      "Jeddah",
      "Mecca",
      "Medina",
      "Dammam",
      "Khobar",
      "Tabuk",
      "Abha",
      "Taif",
      "Hail",
      "Jizan",
      "Najran",
      "Arar",
      "Al Khobar",
      "Qatif",
      "Dhahran",
      "Riyadh",
      "Al-Hasa",
      "Buraidah",
      "Sakaka",
      "Al-Jouf",
      "Khamis Mushait",
      "Umm al-Qura",
      "Al-Qurayyat",
      "Yanbu",
      "Jeddah",
      "Al-Mubarraz",
      "Al-Malaz",
      "Al-Khobar",
      "Al-Ahsa",
      "Al-Kharj",
      "Al-Rass",
    ],
  },
  {
    country: "Algeria",
    cities: [
      "Algiers",
      "Oran",
      "Constantine",
      "Annaba",
      "Blida",
      "Batna",
      "Djelfa",
      "Setif",
      "Tlemcen",
      "Biskra",
      "Ouargla",
      "El Oued",
      "Tiaret",
      "Laghouat",
      "El Khroub",
      "Chlef",
      "Mila",
      "Bouira",
      "Khenchela",
      "Aïn Defla",
      "Aïn Témouchent",
      "Skikda",
      "Guelma",
      "M'sila",
      "Tizi Ouzou",
      "Bejaia",
      "Mostaganem",
      "El Madania",
      "Médéa",
      "Tlemcen",
      "Tipaza",
      "El Harrach",
    ],
  },
  {
    country: "United Arab Emirates",
    cities: [
      "Dubai",
      "Abu Dhabi",
      "Sharjah",
      "Al Ain",
      "Ajman",
      "Ras Al Khaimah",
      "Fujairah",
      "Umm Al Quwain",
      "Khor Fakkan",
      "Dibba Al-Fujairah",
      "Jumeirah",
      "Mirdif",
      "Al Dhafra",
      "Al Ruwais",
      "Al Nakheel",
      "Al Qusais",
      "Al Barsha",
      "Al Satwa",
      "Al Ghusais",
      "Al Jaddaf",
      "Al Karama",
      "Al Muteena",
      "Al Qasba",
      "Deira",
      "Bur Dubai",
      "Mussafah",
      "Al Reem Island",
      "Al Marina",
      "Saadiyat Island",
      "Jebel Ali",
    ],
  },
  {
    country: "Jordan",
    cities: [
      "Amman",
      "Zarqa",
      "Irbid",
      "Russeifa",
      "Aqaba",
      "Madaba",
      "Mafraq",
      "Karak",
      "Jerash",
      "Ma'an",
      "Salt",
      "Tafila",
      "Al-Karak",
      "Al-Zarqa",
      "Wadi Musa",
      "Russeifa",
      "Ajloun",
      "Mafraq",
      "Irbid",
      "Hussein",
      "Wadi Araba",
      "Qatraneh",
      "Al-Hashimiyah",
      "Jarrash",
      "Al-Ramtha",
      "Sahab",
      "Sukhna",
      "Al-Mujib",
      "Aqaba",
      "Baqa'a",
      "Ad-Dlail",
      "Al-Hussein",
    ],
  },
  {
    country: "Lebanon",
    cities: [
      "Beirut",
      "Tripoli",
      "Sidon",
      "Tyre",
      "Zahle",
      "Baalbek",
      "Byblos",
      "Jounieh",
      "Aley",
      "Nabatieh",
      "Zahle",
      "Jbeil",
      "Bchamoun",
      "Kaslik",
      "Hadath",
      "Baabda",
      "Marjeyoun",
      "Hermel",
      "Rachaya",
      "Arsal",
      "Chekka",
      "Batroun",
      "Zouk Mikael",
      "Jadra",
      "Jounieh",
      "Shahin",
      "Ain El Remmaneh",
      "Dbayeh",
      "Chtaura",
      "Rafic Hariri",
    ],
  },
  {
    country: "Tunisia",
    cities: [
      "Tunis",
      "Sfax",
      "Sousse",
      "Ettadhamen",
      "Kairouan",
      "Gabes",
      "Bizerte",
      "Ariana",
      "Gafsa",
      "Monastir",
      "Mahdia",
      "Nabeul",
      "Kasserine",
      "Sidi Bouzid",
      "El Kef",
      "Tozeur",
      "Jendouba",
      "Medenine",
      "Tataouine",
      "La Goulette",
      "Menzel Bourguiba",
      "Medenine",
      "Béja",
      "El Jem",
      "Sousse",
      "Djerba",
      "Kairouan",
      "Nabeul",
      "Siliana",
      "Sidi Bou Said",
      "Ksar Hellal",
      "Menzel Temime",
    ],
  },
  {
    country: "Iraq",
    cities: [
      "Baghdad",
      "Basra",
      "Mosul",
      "Erbil",
      "Sulaymaniyah",
      "Najaf",
      "Kirkuk",
      "Karbala",
      "Nasiriyah",
      "Diwaniyah",
      "Kut",
      "Amara",
      "Hilla",
      "Samawah",
      "Duhok",
      "Rania",
      "Sulaimani",
      "Kifri",
      "Baqubah",
      "Tikrit",
      "Rawa",
      "Fallujah",
      "Al Qaim",
      "Heet",
      "Ramadi",
      "Al-Muqayyar",
      "Haditha",
      "Al-Basrah",
      "Sinjar",
      "Al-Kut",
      "Al-Hillah",
      "Diyala",
      "Khanaqin",
    ],
  },
  {
    country: "Syria",
    cities: [
      "Damascus",
      "Aleppo",
      "Homs",
      "Hama",
      "Latakia",
      "Deir ez-Zor",
      "Al-Hasakah",
      "Qamishli",
      "Daraa",
      "Tartus",
      "Raqqa",
      "Idlib",
      "Palmyra",
      "Douma",
      "Zabadani",
      "Yabroud",
      "Ar-Raqqah",
      "Qunaitra",
      "Hassakeh",
      "Salamiyeh",
      "Alep",
      "Jableh",
      "Dumeir",
      "Manbij",
      "Tel Abyad",
      "Hama",
      "Saraqib",
      "Kafranbel",
      "Kafr Nabl",
      "Kafartin",
      "Kafr Shams",
      "Jisr ash-Shughur",
    ],
  },
  {
    country: "Sudan",
    cities: [
      "Khartoum",
      "Omdurman",
      "Port Sudan",
      "Nyala",
      "Kassala",
      "El Obeid",
      "El Geneina",
      "El Fasher",
      "Sennar",
      "Kosti",
      "Juba",
      "Kadugli",
      "Damazin",
      "Renk",
      "Wadi Halfa",
      "Dongola",
      "Atbara",
      "Merowe",
      "Kassala",
      "El Damar",
      "Heglig",
      "Gadarif",
      "Berber",
      "Shendi",
      "Singa",
      "Tandasi",
      "Ras Sudr",
      "Abu Hamad",
      "Kereinek",
      "Ar Rahad",
      "Jebel Aulia",
      "Ad-Damazin",
    ],
  },
  {
    country: "Yemen",
    cities: [
      "Sanaa",
      "Aden",
      "Taiz",
      "Hodeidah",
      "Ibb",
      "Dhamar",
      "Al Mukalla",
      "Amran",
      "Zabid",
      "Sayun",
      "Rada'a",
      "Lahij",
      "Ma'rib",
      "Shabwa",
      "Hajjah",
      "Al Hudaydah",
      "Baidha",
      "Zinjibar",
      "Dhamar",
      "Al Mahwit",
      "Sanaa",
      "Yarim",
      "Raimah",
      "Dhale",
      "Mokha",
      "Haradh",
      "Hajjah",
      "Seyoun",
      "Taiz",
      "Zinjibar",
      "Amran",
    ],
  },
  {
    country: "Libya",
    cities: [
      "Tripoli",
      "Benghazi",
      "Misrata",
      "Zawiya",
      "Ajdabiya",
      "Bayda",
      "Zliten",
      "Tobruk",
      "Khoms",
      "Sabha",
      "Sirte",
      "Derna",
      "Jalu",
      "Janzour",
      "Bani Walid",
      "Ghat",
      "Ghadames",
      "Nalut",
      "Houn",
      "Sebha",
      "Murzuq",
      "Sabratha",
      "Waddan",
      "Zliten",
      "Rujban",
      "Houn",
      "Ulad al-Husayn",
      "Ghadames",
      "Mizdah",
      "Zuwara",
      "Shahat",
    ],
  },
  {
    country: "Palestine",
    cities: [
      "Jerusalem (Al-Quds)",
      "Gaza",
      "Ramallah",
      "Hebron (Al-Khalil)",
      "Nablus",
      "Bethlehem",
      "Jenin",
      "Tulkarem",
      "Qalqilya",
      "Rafah",
      "Khan Younis",
      "Deir al-Balah",
      "Beit Jala",
      "Jericho (Ariha)",
      "Salfit",
      "Yatta",
      "Dura",
      "Bani Na'im",
      "Beit Sahour",
      "Al-Bireh",
      "Surif",
      "Dheisheh",
      "Shuafat",
      "Husan",
      "Al-Khader",
      "Jalazone",
      "Anabta",
      "Arraba",
      "Jifna",
      "Tuqu",
      "Hares",
    ],
  },
  {
    country: "Kuwait",
    cities: [
      "Kuwait City",
      "Al Ahmadi",
      "Hawalli",
      "Salmiya",
      "Sabah Al Salem",
      "Farwaniya",
      "Mubarak Al-Kabeer",
      "Jahra",
      "Fahaheel",
      "Mangaf",
      "Kaifan",
      "Rai",
      "Shuwaikh",
      "Adailiya",
      "Hawally",
      "Salmiya",
      "Mubarak Al-Kabeer",
      "Jabriya",
      "Bneid Al Gar",
      "Rumaithiya",
      "Yarmouk",
      "Jleeb Al Shuyoukh",
      "Mubarak Al Kabeer",
      "Khaitan",
      "Fahaheel",
      "Jahra",
      "Abu Halifa",
      "Al-Osaimi",
      "Al-Sadd",
      "West Mishref",
      "East Jleeb",
    ],
  },
  {
    country: "Oman",
    cities: [
      "Muscat",
      "Salalah",
      "Sohar",
      "Nizwa",
      "Sur",
      "Barka",
      "Saham",
      "Bawshar",
      "Ibri",
      "Rustaq",
      "Mudhaibi",
      "Sib",
      "Dhalq",
      "Khassab",
      "Shinas",
      "Ibra",
      "Manah",
      "Bilad Sayt",
      "Fanja",
      "Khasab",
      "Al Hamra",
      "Jalan Bani Bu Ali",
      "Jalan Bani Bu Hassan",
      "Al Mudhaibi",
      "Ma'abela",
      "Nizwa",
      "Tanuf",
      "Musannah",
      "Buraimi",
      "Khasab",
    ],
  },
  {
    country: "Qatar",
    cities: [
      "Doha",
      "Al Rayyan",
      "Umm Salal",
      "Al Wakrah",
      "Al Khor",
      "Dukhan",
      "Mesaieed",
      "Lusail",
      "Al Daayen",
      "Al Shamal",
      "Madinat ash Shamal",
      "Madinat Khalifa",
      "Al Wukair",
      "Al Zubara",
      "Al Gharrafa",
      "Al Shafi",
      "Al Khor",
      "Umm Salal Ali",
      "Al Gharafa",
      "Madinat ash Shamal",
      "Al-Maamoura",
      "Al-Najma",
      "Al-Rumaila",
      "Al-Khulaifat",
      "Madinat Khalifa South",
      "Al-Nasr",
      "Muaither",
      "New Doha",
      "Fereej Al Soudan",
      "Qatar University",
    ],
  },
  {
    country: "Bahrain",
    cities: [
      "Manama",
      "Riffa",
      "Muharraq",
      "Hamad Town",
      "Isa Town",
      "Sitra",
      "Budaiya",
      "Jidhafs",
      "Sanad",
      "Adliya",
      "Galali",
      "A'ali",
      "Saar",
      "Hidd",
      "Malkiya",
      "Ramez",
      "Juffair",
      "Salmaniya",
      "Al-Bidaa",
      "Shakhoora",
      "Busaiteen",
      "Al-Khobar",
      "Muharraq",
      "Bahrain Bay",
      "Naim",
      "Al-Muharraq",
      "Nasser Town",
      "Jid Ali",
      "Al Malkiya",
      "Al Seef",
      "Riffa",
    ],
  },
  {
    country: "Mauritania",
    cities: [
      "Nouakchott",
      "Nouadhibou",
      "Rosso",
      "Kaedi",
      "Zouerate",
      "Atar",
      "Nema",
      "Aleg",
      "Kiffa",
      "Tidjikja",
      "Boutilimit",
      "Moghrein",
      "Aoujeft",
      "Chinguetti",
      "Boutilimit",
      "El Mreiti",
      "Tichit",
      "Monguel",
      "El Khadra",
      "El Gorgol",
      "Aoujeft",
      "Ksar el-Bghal",
      "Baleidat",
      "Aghor",
      "Amour",
      "Tagant",
      "Al-Aaiun",
      "Tazadit",
      "Aghor",
      "El Maader",
    ],
  },
  {
    country: "Somalia",
    cities: [
      "Mogadishu",
      "Hargeisa",
      "Bosaso",
      "Kismayo",
      "Garoowe",
      "Baidoa",
      "Beledweyne",
      "Berbera",
      "Jowhar",
      "Galkayo",
      "Burao",
      "Las Anod",
      "Dhusa Mareb",
      "Eyl",
      "Shinile",
      "Adado",
      "Balcad",
      "Buhoodle",
      "Luuq",
      "Afgooye",
      "Hobyo",
      "Hiraan",
      "Jamaame",
      "Kalimado",
      "Kandala",
      "Qardho",
      "Ruqd",
      "Abudwak",
      "Sool",
      "Wajale",
      "Samaroon",
    ],
  },
  {
    country: "Djibouti",
    cities: [
      "Djibouti City",
      "Ali Sabieh",
      "Tadjoura",
      "Arta",
      "Dikhil",
      "Obock",
      "Loyada",
      "Balho",
      "Yoboki",
      "Randa",
      "Bali",
      "Khor Angar",
      "Goubetto",
      "Ali Sabieh",
      "Mabla",
      "Holl-Holl",
      "Bale",
      "Hodan",
      "Mouloud",
      "Holl-Holl",
      "Obock",
      "Bani",
      "Yoboki",
      "Randa",
      "Dikhil",
      "Loyada",
      "Goubetto",
      "Khor Angar",
      "Tadjoura",
      "Arta",
      "Ali Sabieh",
    ],
  },
  {
    country: "Comoros",
    cities: [
      "Moroni",
      "Mutsamudu",
      "Fomboni",
      "Domoni",
      "Tsémbéhou",
      "Ouani",
      "Nioumachoua",
      "Bimbini",
      "Barakani",
      "Moya",
      "Ikoni",
      "Mwali",
      "Ouani",
      "Dzaoudzi",
      "Bandrélé",
      "Dziani",
      "Koungou",
      "Mtsangamouji",
      "Sima",
      "Hoani",
      "Chindini",
      "Mboudé",
      "Mitsamiouli",
      "Sima",
      "Chindini",
      "Kounoune",
      "Sangani",
      "Hani",
      "Gombani",
      "Kafoudjane",
      "Mshimba",
    ],
  },
];

export default function getCities(country: string) {
  return arabCountriesCities.find((c) => c.country === country)?.cities || [];
}
